### ISSUE TITLE
Customize 404 page

### ISSUE THREAD

**Issue by LBLucaBonetti** [LBLucaBonetti/daily#226]
The actual 404 page is the standard one provided by Quasar. Customize it to make it coherent with the design

**Comment by GanLiuuuu** [comment]
Hello! I'm interested in this issue. Can I contribute to it? If so, could you please describe the style it should be? Thanks!

**Comment by LBLucaBonetti** [comment]
Hello and thanks for your interest in my project. I would like it to look like the rest of the app, so it should have the same color palette (mainly orangish and whitish) and be responsive. I would place a customized image from unDraw in the center and make sure the size is appropriate to be correctly displayed at each screen size. You can then make a pull request and I will take care of the review

**Comment by GanLiuuuu** [comment]
Thank you for the reply. I’m working on that project now and hopefully it can meet your standards.

**Comment by LBLucaBonetti** [comment]
@GanLiuuuu I'm really sorry but since I received no updates on this for a long period of time I decided to do it by myself
